# Generated by Django 3.1.7 on 2021-04-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_projects_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
